### ISSUE TITLE
All the choices being the same(correct answer) in the 'Fill in the blanks' game

### ISSUE THREAD

**Issue by deonchimple** [chimple/maui#616]
Sometimes we have the all the choices that would be the same and in rare cases, There would be all empty blank spaces. 

![screenshot_2018-07-24-10-59-30-329_sutara org maui](https://user-images.githubusercontent.com/35517512/43118815-38c96e26-8f31-11e8-8d61-9c00c0e88b28.png)

**Comment by rishabh-chimple** [comment]
It's okay
