### ISSUE TITLE
Match the following- Multi touch issues (Blocker)

### ISSUE THREAD

**Issue by Prakhar2403** [chimple/maui#795]
### **Last Build Time: 11.40 am  &  Date:27/08/2018**
![screenshot_2018-08-27-10-27-23-640_sutara org maui](https://user-images.githubusercontent.com/19926827/44642067-226ee580-a9e8-11e8-80fc-f97eba2e9e0c.png)
![screenshot_2018-08-27-10-30-24-509_sutara org maui](https://user-images.githubusercontent.com/19926827/44642068-26026c80-a9e8-11e8-8a14-cf456cad3514.png)
![screenshot_2018-08-27-10-30-28-863_sutara org maui](https://user-images.githubusercontent.com/19926827/44642075-2ac72080-a9e8-11e8-8fad-6960a0978c49.png)

**Comment by sutara-aayush** [comment]
Please Let me know the output coming on console, then i will be able to judge what actually is causing this issue
