### ISSUE TITLE
Unwanted image auto save issue (Draw Activity)

### ISSUE THREAD

**Issue by Prakhar2403** [chimple/maui#856]
### **It automatically saving the default image multiple times to the image gallery with the desired image save by user.**

![image autosave](https://user-images.githubusercontent.com/19926827/45341806-7ae1dd80-b5b9-11e8-9bcc-69db0049ded9.png)

**Comment by talapadi** [comment]
Should be fixed now with the changes in JSON saving

**Comment by Prakhar2403** [comment]
Not fixed

**Comment by Prakhar2403** [comment]
Fixed
