### ISSUE TITLE
Keyboard issue (Tahiti)

### ISSUE THREAD

**Issue by Biswajeet-chimple** [chimple/maui#859]
Scenario 1: When Drawing activity is opened for the first time then keyboard opens up by default and the stickers, text are not working.

Scenario 2: When Drawing activity is opened and when user taps on add template button and selects the template and user taps on text(abc) then error is shown.

![1](https://user-images.githubusercontent.com/35517569/45342867-d6619a80-b5bc-11e8-980e-c4a58d588f72.png)

**Comment by talapadi** [comment]
Should be fixed now

**Comment by Biswajeet-chimple** [comment]
scenario changed as new ui has been developed
