### ISSUE TITLE
Drawing activity Sticker issue 

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#860]
when the user is using colored Stricker by pressing the add button (+) and when the user is pressing the back button, the stickers are getting invisible.
Steps to reproduce:
1. go to Maui app and to the article page in the animal category.
2. then select the related page and go inside the related page.
3. press the + button and select any color other than white and select any sticker from it.
4. then press page back button and again come back the same page.
*the sticker will not be there.  
![screenshot_1536649155](https://user-images.githubusercontent.com/35517554/45343583-eb3f2d80-b5be-11e8-8529-7cabc97c4c30.png)
![screenshot_1536649163](https://user-images.githubusercontent.com/35517554/45343589-ed08f100-b5be-11e8-95c7-7840641ccc84.png)

**Comment by talapadi** [comment]
Should be fixed with the new UI
