### ISSUE TITLE
Paint shown after tapping back and returning to the same page(tahiti)

### ISSUE THREAD

**Issue by Biswajeet-chimple** [chimple/maui#864]
Steps to reproduce:
1.Go to drawing activity page
2.Tap on saved drawings page
3.Tap back
4.Select paint and draw on the page(nothing is displayed what has been drawn)
5.Tap back 
6. Then return to the drawing page(the missing paint is displayed on the screen).

**Comment by talapadi** [comment]
Since navigation is now changed, this should be fixed
