### ISSUE TITLE
replace the undo and redo button(enhancement)(change the position)

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#869]
1. go to Maui Application and go to activity drawing page.
2. now place one sticker on the undo or redo button and leave the mouse cursor.
3. now again pick the same sticker 
   you will see you can't pick the sticker because it is behind the undo and redo button. 
*so the simple solution is to place the undo and redo button somewhere else with stickers button.

**Comment by talapadi** [comment]
The new UI should have fixed this
