### ISSUE TITLE
error is coming when resizing the sticker with red dots

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#870]
Steps to reproduce:
1. go to Maui Application and go to activity drawing page.
2. now select one sticker and try to resize it (make it small as small as possible through red dots )
3. it will through an error
![screenshot_1537164961](https://user-images.githubusercontent.com/35517554/45608216-46fe3080-ba6f-11e8-816d-7b0ccb01d8ee.png)

**Comment by AvinashPratap** [comment]
it should not resize the sticker with the single touch for text it is ok

**Comment by talapadi** [comment]
Please retest and see if this is still happening
