### ISSUE TITLE
issue with text input in Drawing Acitvity Page

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#871]
Step to reproduce:
1. go to Maui application and go to Drawing Activity Page.
2. Select Abc text button and leave as it is don't type anything. 
3. now save it and go to the saved one's page.
 *   first of all the keyboard  will open Automatically and the second user is able to write the text 
![screenshot_1537165393](https://user-images.githubusercontent.com/35517554/45608496-deb04e80-ba70-11e8-929c-125d121c2b9d.png)

**Comment by talapadi** [comment]
Should be fixed now with the new keyboard component
