### ISSUE TITLE
Text is not working 

### ISSUE THREAD

**Issue by Hemalatha195** [chimple/maui#893]
Step to reproduce the bug
Open Maui Application
go to the activity page 
click on Text and select font for text
click on the edit text

Summary: after clicking on edit just a keyboard is popping up and some error screen is coming.
![screenshot_1537853771](https://user-images.githubusercontent.com/35517508/45994840-10e62f80-c0b3-11e8-8c91-d0e062b18a71.png)

**Comment by talapadi** [comment]
Should be fixed now
