### ISSUE TITLE
exception is coming when user is going inside the Quiz game (category Quizzes)

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#896]
Steps to reproduce:-
1. go to Maui application and category option.
2. select any of the categories and go inside the game of that particular category. 
3. when you will click on an uppercase letter.
 * it will throw an exception saying "cast method called on null"
![screenshot_1537936433](https://user-images.githubusercontent.com/35517554/46058113-ef4e7c00-c176-11e8-9190-f4a38af85d04.png)

**Comment by talapadi** [comment]
Fixed for now
