### ISSUE TITLE
Saved drawings  are not coming in the Gallery

### ISSUE THREAD

**Issue by Hemalatha195** [chimple/maui#898]
Step to reproduce the bug
1.go to the activity screen 
2: draw on the canvas and saved it
3; take a new canvas
4: again save it 
5: go to the saved gallery
Summary: Error screen is coming on the gallery items when it tries to save the second drawings.
![gallery](https://user-images.githubusercontent.com/35517508/46059094-6980ff80-c17b-11e8-88cb-a1e8fe33fe4e.png)

**Comment by talapadi** [comment]
GlobalKey has been removed from Tahiti paper. This should be fixed now.
