### ISSUE TITLE
an issue in the home page

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#915]
Steps to reproduce:
1. go to Maui app and go to the homepage.
2. now keep on clicking and clicking on "like" button.
* you will see different exceptions and bugs.
 a. one user can like the other person post 
     multiple times.
 b. when you keep on pressing it will throw an 
     exception.
 c. sometimes the screen become blank.
![screenshot_1538200627](https://user-images.githubusercontent.com/35517554/46241811-b1529180-c3dc-11e8-8e21-48e8c69568b2.png)
![screenshot_1538200645](https://user-images.githubusercontent.com/35517554/46241814-bdd6ea00-c3dc-11e8-94e5-ff2d00955146.png)
![screenshot_1538200495](https://user-images.githubusercontent.com/35517554/46241756-ed392700-c3db-11e8-89c3-791f8489663f.png)

**Comment by talapadi** [comment]
Since home page and comments have been revamped, this should not be reproducible
