### ISSUE TITLE
because of the home page, category page is also throwing an exception.

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#916]
Steps to reproduce:
1. go to Maui app and go to the homepage.
2. now keep on clicking and clicking on "like" button.
3. you will see different exceptions and when it comes, go to the category page and click on any of the categories.
 * you will see exception occurs and that to 
   blocker.
    
![screenshot_1538201759](https://user-images.githubusercontent.com/35517554/46241901-4609bf00-c3de-11e8-83d5-5f7dc0085698.png)

**Comment by talapadi** [comment]
Since home page and comments have been revamped, this should not be reproducible
