### ISSUE TITLE
Undo button activates without drawing on saved drawing gallery

### ISSUE THREAD

**Issue by Biswajeet-chimple** [chimple/maui#920]
Steps to reproduce:
1. Open saved drawing from template gallery where already paint or erase action is already done.
2. Drag on the saved drawing without selecting any tool.
3. Undo gets activated and is able to undo paint done previously.

**Comment by AvinashPratap** [comment]
it is also happening when selecting the new drawing template and dragging the finger in the sheet without selecting any of the brushes, the undo button activates automatically.

**Comment by Prakhar2403** [comment]
Working as expected. Fixed
