### ISSUE TITLE
Home page comment section displays error message 

### ISSUE THREAD

**Issue by Prakhar2403** [chimple/maui#928]
### Steps to reproduce:
1.go to Maui app and go to the homepage.
2. then go to 'comment' & click 'submit' button.

Expected: It throws exception & display error message , which act as a 'blocker'.

![3868598078392807630](https://user-images.githubusercontent.com/19926827/46391066-a22f5480-c6f8-11e8-9ca7-93d745391d57.png)

**Comment by talapadi** [comment]
Since home page and comments have been revamped, this should not be reproducible
