### ISSUE TITLE
Home page comment box got disappeared

### ISSUE THREAD

**Issue by Prakhar2403** [chimple/maui#953]
**Steps to reproduce:**
1.go to Maui app and go to the home page.
2. then go to 'comment', type something & click 'submit' button.
3. then go back to home page.

**Expected: Comment box got disappeared from the home page.**

![comment error](https://user-images.githubusercontent.com/19926827/46648786-37789000-cbb4-11e8-9955-31f2729e102a.png)

**Comment by talapadi** [comment]
May not be an issue now.
