### ISSUE TITLE
navigation issue, when the user is clicking on the already read article shown in the home page.

### ISSUE THREAD

**Issue by AvinashPratap** [chimple/maui#962]
Steps to reproduce:-
1. go to Maui and open category page.
2. select any of the subcategories and read the article about that particular subcategory.
3. now come to the home page search for that article you had read and click on it.
* it will throw an exception
![screenshot_20181019-111138](https://user-images.githubusercontent.com/35517554/47199724-926a6e00-d390-11e8-9125-573a39785d76.png)

**Comment by Prakhar2403** [comment]
Fixed
